'use client';
import {Header,Footer} from '@/components/verba-ui';
import {useT} from '@/components/i18n';
import {details} from '@/lib/catalog';
import {appHref} from '@/lib/links';
import {Stethoscope,Scale,ChartNoAxesCombined,Code2,Megaphone,Check} from 'lucide-react';
const icons=[Stethoscope,Scale,ChartNoAxesCombined,Code2,Megaphone];
const steps:[string,string][]=[['Tell us what you need','Choose a service, your languages and documents. Get a price online before you commit.'],['Confirm the details','Sign in or create an account and confirm the order. We review your documents and confirm the final scope, fees and delivery date.'],['Keep everything together','Follow progress, chat with customer service and download completed files from your personal area.']];
export default function Services(){const {t}=useT();return <><Header/><main className="services-page"><section className="services-hero"><span className="eyebrow">{t('BUILT FOR THE WORDS THAT MATTER')}</span><h1>{t('Context changes everything.')}<br/><span>{t('So should your translation.')}</span></h1><p>{t('A clinical finding. A contractual obligation. A brand promise.')}<br/>{t('Choose a workflow that respects what your words need to do.')}</p><a className="button primary" href={appHref('/order')}>{t('Estimate your project')}</a></section><div className="expertise-grid">{details.map((d,i)=>{const Icon=icons[i];return <article key={d.name} className={'expertise-card expertise-'+i}><div className="expertise-top"><Icon size={30}/><span>0{i+1}</span></div><span className="small-kicker">{t(d.name)}</span><h2>{t(d.tag)}</h2><p>{t(d.text)}</p><a href={appHref('/order')}>{t('Start a {field} project',{field:t(d.name).toLowerCase()})}</a></article>;})}<article className="expertise-card dark-card"><span className="small-kicker">{t('BEYOND TRANSLATION')}</span><h2>{t('From first file')}<br/>{t('to final delivery.')}</h2><p>{t('Add independent validation, request notarial certification or arrange document collection in the same order.')}</p><a href={appHref('/order')}>{t('Explore all eight services')}</a></article></div><section id="process" className="process-section"><div><span className="eyebrow">{t('A CLEARER WAY TO WORK')}</span><h2>{t('Less back-and-forth.')}<br/>{t('More moving forward.')}</h2></div><div className="process-list">{steps.map(([title,text],i)=><div key={title}><span>0{i+1}</span><section><h3>{t(title)}</h3><p>{t(text)}</p></section></div>)}</div></section><div className="service-disclosure"><Check size={20}/><p>{t('Verba provides the ordering and review workflow. Specialist qualifications, availability and jurisdiction-specific certification must be verified by the service operator before accepting work.')}</p></div></main><Footer/></>;}
