import assert from 'node:assert/strict';
import {newOrder,orderSchema,quote,defaultPricing} from '../lib/catalog.ts';
const draft={...newOrder(),title:'Synthetic medical translation',name:'Test Customer',email:'owner@example.test',phone:'+972500000000',agreed:true};
assert.equal(quote(draft).total,5980);
assert.equal(quote({...draft,urgency:'Express'}).total,8970);
assert.equal(quote({...draft,targets:['Hebrew','French']}).total,11180);
assert.equal(quote({...draft,documents:[{...draft.documents[0],words:0,pages:2}]}).words,500);
assert.equal(orderSchema.safeParse({...draft,targets:['English']}).success,false);
assert.equal(orderSchema.safeParse({...draft,level:'Student'}).success,false);
assert.equal(orderSchema.safeParse({...draft,delivery:true}).success,false);
assert.equal(orderSchema.safeParse({...draft,documents:[{...draft.documents[0],words:-1}]}).success,false);
assert.equal(quote({...draft,service:'Courier only'}).total,2500);
assert.equal(quote({...draft,service:'Additional services'}).manual,true);
assert.equal(quote({...draft,service:'Notary only',copies:2,documents:[draft.documents[0],draft.documents[0]]}).total,18000);
console.log('PASS: 11 pricing and validation assertions');
import {startApp,caller} from './support/harness.mjs';
const app=await startApp({name:'workflows'});
let count=0;
const identity={owner:['owner-test','owner@example.test'],outsider:['outsider-test','outsider@example.test'],notary:['notary-test','notary@example.test'],courier:['courier-test','courier@example.test']};
const call=caller(app,identity);
function check(actual,expected,label){assert.equal(actual,expected,label);count++;}
try{
check((await call('/api/orders',{actor:null})).status,401,'anonymous rejected');
check((await call('/api/workspace')).status,200,'workspace initializes');
check((await call('/api/setup')).data.connected,false,'unconfigured provider disclosed');
const noKey=await call('/api/translations',{method:'POST',body:{requestKey:crypto.randomUUID(),title:'No key test',source:'English',target:'French',sector:'Medical',tone:'Faithful',text:'Synthetic source',consent:true}});check(noKey.status,201,'quote request does not require provider');const quoted=await call('/api/translations/'+noKey.data.id+'/advance',{method:'POST',body:{}});check(quoted.data.state,'quoted','quote without provider');check((await call('/api/translations/'+noKey.data.id,{method:'PATCH',body:{action:'accept_quote',accepted:true,version:quoted.data.version,quoteId:quoted.data.quote.id}})).status,503,'unconfigured provider cannot start translation');
const created=await call('/api/orders',{method:'POST',body:{payload:draft,submit:false,total:1}});check(created.status,201,'quote creates');check(created.data.total,5980,'client price is ignored');const id=created.data.id;
check((await call('/api/orders/'+id)).status,200,'owner reads');check((await call('/api/orders/'+id,{actor:'outsider'})).status,404,'tenant isolation');
check((await call('/api/orders',{method:'POST',headers:{origin:'https://evil.example'},body:{payload:draft}})).status,403,'cross-origin writes denied');
check((await call('/api/orders',{method:'POST',body:{payload:{...draft,targets:['English']}}})).status,400,'invalid language rejected');
const edit=await call('/api/orders/'+id,{method:'PUT',body:{payload:{...draft,title:'Updated synthetic record'},submit:false}});check(edit.status,200,'draft edit');check((await call('/api/orders/'+id)).data.payload.title,'Updated synthetic record','edit persists');
check((await call('/api/orders/'+id,{method:'PATCH',body:{status:'Delivered'}})).status,409,'cannot skip workflow');
check((await call('/api/orders/'+id,{method:'PATCH',body:{shipment:'Assigned',courier:'courier@example.test'}})).status,400,'courier assignment requires eligible member');
check((await call('/api/orders/'+id,{method:'PATCH',body:{shipment:'Assigned'}})).status,400,'shipment not included denied');
check((await call('/api/orders/'+id,{method:'PATCH',body:{status:'Submitted'}})).status,200,'submit');
check((await call('/api/orders/'+id,{method:'PUT',body:{payload:draft}})).status,409,'submitted order not editable as draft');
check((await call('/api/orders/'+id,{method:'PATCH',body:{status:'In review'}})).status,200,'review');
check((await call('/api/orders/'+id,{method:'PATCH',body:{status:'Ready'}})).status,400,'cannot mark ready without output');
check((await call('/api/messages',{method:'POST',body:{orderId:id,body:'Test terminology note'}})).status,201,'message saved');
check((await call('/api/messages',{actor:'outsider',method:'POST',body:{orderId:id,body:'Unauthorized'}})).status,404,'message isolation');
const invalid=new FormData();invalid.set('file',new File(['not a pdf'],'invalid.pdf'));check((await call('/api/files',{method:'POST',body:invalid})).status,400,'invalid file signature');
const form=new FormData();form.set('file',new File(['Synthetic translation text'],'translation.txt',{type:'text/plain'}));form.set('orderId',id);form.set('purpose','delivery');const upload=await call('/api/files',{method:'POST',body:form});check(upload.status,201,'result upload');check((await call('/api/files/'+upload.data.id)).status,200,'authorized download');check((await call('/api/files/'+upload.data.id,{actor:'outsider'})).status,404,'download isolation');
check((await call('/api/team',{method:'POST',body:{name:'Test Notary',email:'notary@example.test',role:'notary',area:''}})).status,200,'staff authorization');
check((await call('/api/workspace',{actor:'notary'})).data.role,'notary','staff has assigned role');
check((await call('/api/workspace',{actor:'notary',method:'PATCH',body:{pricing:defaultPricing,name:'Intrusion'}})).status,403,'staff cannot edit prices');
check((await call('/api/orders/'+id,{actor:'notary'})).status,403,'unassigned notary denied');
check((await call('/api/orders/'+id,{method:'PATCH',body:{assignee:'notary@example.test',status:'Notary review'}})).status,200,'assign notary');
check((await call('/api/orders/'+id,{actor:'notary'})).status,200,'assigned notary access');
check((await call('/api/orders/'+id,{actor:'notary',method:'PATCH',body:{status:'Ready'}})).status,200,'notary completes review');
check((await call('/api/orders/'+id,{method:'PATCH',body:{status:'Delivered'}})).status,200,'final delivery');
const saved=await call('/api/orders/'+id);check(saved.data.payment,'Not requested','never fakes payment');check(saved.data.messages.length,1,'message persistence');assert(saved.data.events.length>=7);count++;
for(const route of ['/','/account','/order','/services','/terms','/privacy','/studio']){const page=await call(route);check(page.status,200,'SSR '+route);assert(!String(page.data).includes('Internal Server Error'));count++;}
check((await call('/api/team',{method:'POST',body:{name:'Test Courier',email:'courier@example.test',role:'courier',area:'Test area'}})).status,200,'authorize courier');
const shipping=await call('/api/orders',{method:'POST',body:{payload:{...draft,title:'Private medical title',notes:'Private clinical notes',delivery:true,pickup:{...draft.pickup,city:'Town',street:'One'},dropoff:{...draft.dropoff,city:'Town',street:'Two'}},submit:true}});check(shipping.status,201,'delivery project');
check((await call('/api/orders/'+shipping.data.id,{method:'PATCH',body:{courier:'courier@example.test',shipment:'Assigned'}})).status,200,'assign shipment');
const courierView=await call('/api/orders/'+shipping.data.id,{actor:'courier'});check(courierView.data.payload.title,'Document delivery','courier title redacted');check(courierView.data.payload.notes,'','courier clinical notes redacted');check(courierView.data.payload.documents.length,0,'courier document metadata redacted');check(courierView.data.messages.length,0,'courier no project discussion');
check((await call('/api/messages',{actor:'courier',method:'POST',body:{orderId:shipping.data.id,body:'No document conversation access'}})).status,403,'courier message access denied');
check((await call('/api/orders/'+shipping.data.id,{actor:'courier',method:'PATCH',body:{shipment:'Collected'}})).status,200,'courier collects');check((await call('/api/orders/'+shipping.data.id,{actor:'courier',method:'PATCH',body:{shipment:'Delivered'}})).status,409,'courier cannot skip transit');
check(String((await call('/studio/summary/'+shipping.data.id,{actor:'courier'})).data).includes('Private clinical notes'),false,'print redacts clinical notes');
console.log(`PASS: ${count} integration and page-render assertions`);
}catch(e){console.error(app.logs().slice(-4000));throw e;}finally{await app.stop();}
