import {context,failure,HttpError} from '@/lib/server';
import {renderPdf} from '@/lib/pdf';
import {makeT} from '@/lib/i18n/core';
import {z} from 'zod';
// Turns the rows currently shown in a report table into a PDF (spec 1.12, 1.16: export to PDF).
export async function POST(r:Request){try{const c=await context(r);const p=z.object({title:z.string().max(120),subtitle:z.string().max(200).default(''),head:z.array(z.string().max(60)).min(1).max(20),rows:z.array(z.array(z.string().max(300)).max(20)).max(3000),lang:z.enum(['en','he']).default('en')}).safeParse(await r.json());
  if(!p.success)throw new HttpError(400,'The report is too large to export. Narrow the search first.');const t=makeT(p.data.lang);
  const pdf=await renderPdf({lang:p.data.lang,landscape:p.data.head.length>5,title:p.data.title,subtitle:[p.data.subtitle,c.workspace.name,new Intl.DateTimeFormat(p.data.lang==='he'?'he-IL':'en-GB',{dateStyle:'long'}).format(new Date())].filter(Boolean).join(' · '),blocks:[{kind:'table',head:p.data.head,rows:p.data.rows}],footer:t('Generated by Verba for {name}',{name:c.u.fullName}),pageLabel:(n,total)=>t('Page {n} of {total}',{n,total})});
  return new Response(Buffer.from(pdf),{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="verba-report.pdf"','Cache-Control':'private, no-store'}});}catch(e){return failure(e);}}
