import {headers} from 'next/headers';
import {redirect} from 'next/navigation';
import {db} from './runtime';
import {randomToken,tokenHash,safeReturnPath} from './account-crypto';
export type AppUser={userId:string;displayName:string;fullName:string;email:string;firstName:string;lastName:string;phone:string|null;company:string;customerType:string;country:string;address:string;language:string;notify:string;currency:string;emailVerified:boolean};
export const SESSION_COOKIE='__Host-verba_session';
export const GUEST_COOKIE='verba_guest';
type AccountRow={id:string;email:string;name:string;first_name:string;last_name:string;phone:string|null;company:string;customer_type:string;country:string;address:string;language:string;notify:string;currency:string;email_verified_at:string|null};
export const toUser=(row:AccountRow):AppUser=>({userId:row.id,email:row.email,fullName:row.name,displayName:row.name,firstName:row.first_name,lastName:row.last_name,phone:row.phone,company:row.company,customerType:row.customer_type,country:row.country,address:row.address,language:row.language,notify:row.notify,currency:row.currency,emailVerified:!!row.email_verified_at});
export function readCookie(cookieHeader:string|null|undefined,name:string){return cookieHeader?.split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1);}
export async function getUser():Promise<AppUser|null>{const h=await headers();const raw=readCookie(h.get('cookie'),SESSION_COOKIE);if(!raw||!/^[a-f0-9]{64}$/.test(raw))return null;const row=await db().prepare('SELECT a.* FROM accounts a JOIN sessions s ON s.account_id=a.id WHERE s.token_hash=? AND s.expires>? AND a.disabled_at IS NULL').bind(tokenHash(raw),new Date().toISOString()).first<AccountRow>();return row?toUser(row):null;}
export async function requireUser(returnTo:string){const u=await getUser();if(u)return u;redirect('/account?return_to='+encodeURIComponent(safeReturnPath(returnTo)));}
// "Remember me" keeps the session for 30 days; otherwise it lasts until the browser closes (and at most 12 hours).
export async function createSession(accountId:string,remember=true){const token=randomToken();const ttl=remember?30*86400000:12*3600000;await db().prepare('INSERT INTO sessions (token_hash,account_id,expires,created) VALUES (?,?,?,?)').bind(tokenHash(token),accountId,new Date(Date.now()+ttl).toISOString(),new Date().toISOString()).run();return `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax${remember?'; Max-Age='+ttl/1000:''}`;}
export async function revokeSession(){const h=await headers();const token=readCookie(h.get('cookie'),SESSION_COOKIE);if(token)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(tokenHash(token)).run();}
export async function authLimit(key:string,max=10,windowMinutes=15){const bucket=Math.floor(Date.now()/(windowMinutes*60000));const id=tokenHash(key+':'+windowMinutes+':'+bucket);const row=await db().prepare('INSERT INTO auth_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=auth_limits.count+1 RETURNING count').bind(id,new Date(Date.now()+windowMinutes*120000).toISOString()).first<{count:number}>();return (row?.count||0)<=max;}
// Visitors can upload documents before signing in. Their files are tied to a private
// browser token and move to the account when they sign in or register.
export async function guestKey(create=false):Promise<{key:string|null;cookie?:string}>{const h=await headers();const raw=readCookie(h.get('cookie'),GUEST_COOKIE);if(raw&&/^[a-f0-9]{64}$/.test(raw))return {key:'guest:'+tokenHash(raw)};if(!create)return {key:null};const token=randomToken();return {key:'guest:'+tokenHash(token),cookie:`${GUEST_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`};}
export async function claimGuestFiles(accountId:string){const {key}=await guestKey();if(!key)return 0;const member=await db().prepare('SELECT m.workspace FROM members m JOIN accounts a ON a.email=m.email WHERE a.id=? ORDER BY CASE m.role WHEN \'admin\' THEN 0 ELSE 1 END LIMIT 1').bind(accountId).first<{workspace:string}>();const r=await db().prepare('UPDATE files SET owner=?, workspace=COALESCE(?, workspace) WHERE owner=? AND order_id IS NULL').bind(accountId,member?.workspace||null,key).run();await db().prepare('UPDATE conversations SET account_id=?, guest_hash=NULL WHERE guest_hash=? AND account_id IS NULL').bind(accountId,key).run();return r.meta.changes;}
