import { z } from 'zod';
export const sectors = ['Medical','Legal','Finance','Technology','Marketing'] as const;
export const languages = ['English','Hebrew','Arabic','French','German','Spanish','Italian','Portuguese','Russian','Bulgarian','Ukrainian','Chinese','Japanese'] as const;
export const services = ['Document translation','Translation + notary','Translation validation','Certificate translation','Certificate + notary','Notary only','Additional services','Courier only'] as const;
export const statuses = ['Draft','Submitted','In review','Translating','Notary review','Ready','Delivered','Cancelled'] as const;
export const details = [
 {name:'Medical',tag:'Every detail matters.',text:'Medical records, clinical research and patient information. Preserve terminology, dosage and meaning.',icon:'medical'},
 {name:'Legal',tag:'Keep the intent intact.',text:'Contracts, court documents and certificates, with a clear route to notarial review.',icon:'legal'},
 {name:'Finance',tag:'Precision beyond the numbers.',text:'Financial reports, investor communications and disclosures with consistent terminology.',icon:'finance'},
 {name:'Technology',tag:'Make complexity clear.',text:'Software, technical documentation and product guides that speak your users’ language.',icon:'technology'},
 {name:'Marketing',tag:'The same idea. A new audience.',text:'Websites, campaigns and brand content adapted for the people you want to reach.',icon:'marketing'},
];
const address = z.object({country:z.string().max(80).default('Israel'),city:z.string().max(100).default(''),street:z.string().max(200).default(''),postcode:z.string().max(30).default(''),contact:z.string().max(100).default(''),phone:z.string().max(40).default(''),window:z.string().max(100).default(''),notes:z.string().max(500).default('')});
export const documentSchema = z.object({name:z.string().min(1).max(160),type:z.string().max(100),pages:z.number().int().min(1).max(10000),words:z.number().int().min(0).max(1000000),format:z.enum(['PDF','DOCX','TXT','JPG','PNG']),fileIds:z.array(z.string().uuid()).max(10).default([])});
export const orderSchema = z.object({title:z.string().min(2).max(160),service:z.enum(services),sector:z.enum(sectors),source:z.enum(languages),targets:z.array(z.enum(languages)).min(1).max(8),documents:z.array(documentSchema).min(1).max(20),level:z.enum(['Professional','Student','Machine draft']),urgency:z.enum(['Standard','Priority','Express']),validation:z.boolean(),notaryType:z.enum(['Translation certification','Signature verification','Certified copy','Affidavit']),copies:z.number().int().min(1).max(20),physical:z.boolean(),delivery:z.boolean(),pickup:address,dropoff:address,name:z.string().min(2).max(120),email:z.string().email(),phone:z.string().max(40),notes:z.string().max(4000),agreed:z.boolean(),currency:z.enum(['EUR','USD','ILS'])}).superRefine((v,ctx)=>{if(v.targets.includes(v.source)&&!['Notary only','Courier only','Additional services'].includes(v.service))ctx.addIssue({code:'custom',message:'Source and target languages must be different',path:['targets']});if((v.delivery||v.service==='Courier only')&&(!v.pickup.city||!v.pickup.street||!v.dropoff.city||!v.dropoff.street||!v.phone))ctx.addIssue({code:'custom',message:'Complete both delivery addresses and a contact phone number',path:['pickup']});if(v.sector==='Medical'&&v.level!=='Professional')ctx.addIssue({code:'custom',message:'Medical documents require the professional workflow',path:['level']});});
export type OrderInput=z.infer<typeof orderSchema>;
export const blankAddress={country:'Israel',city:'',street:'',postcode:'',contact:'',phone:'',window:'09:00–17:00',notes:''};
export function newOrder():OrderInput{return {title:'',service:'Document translation',sector:'Medical',source:'English',targets:['Hebrew'],documents:[{name:'Document 1',type:'Document',pages:1,words:250,format:'PDF',fileIds:[]}],level:'Professional',urgency:'Standard',validation:true,notaryType:'Translation certification',copies:1,physical:false,delivery:false,pickup:{...blankAddress},dropoff:{...blankAddress},name:'',email:'',phone:'',notes:'',agreed:false,currency:'EUR'};}
export const defaultPricing={professional:0.14,student:0.08,machine:0.03,validation:0.04,notary:75,copy:15,delivery:25,minimum:25,usd:1.10,ils:4.00};
export const pricingSchema=z.object(Object.fromEntries(Object.keys(defaultPricing).map(k=>[k,z.number().min(0.001).max(10000)])) as Record<keyof typeof defaultPricing,z.ZodNumber>);
export function quote(o:OrderInput,p=defaultPricing){const words=o.documents.reduce((n,d)=>n+(d.words||d.pages*250),0);const translates=!['Notary only','Courier only','Additional services'].includes(o.service);const specialist={Medical:1.2,Legal:1.15,Finance:1.1,Technology:1.05,Marketing:1}[o.sector];const rate=o.level==='Professional'?p.professional:o.level==='Student'?p.student:p.machine;const languageFactor=o.targets.reduce((n,l)=>n+(['Japanese','Chinese','Arabic','Hebrew'].includes(l)?1.15:1),0);const base=translates?Math.max(p.minimum,words*(o.service==='Translation validation'?p.validation:rate)*specialist*languageFactor):0;const review=translates&&o.validation&&o.service!=='Translation validation'?words*p.validation*languageFactor:0;const rush=(base+review)*({Standard:0,Priority:0.25,Express:0.5}[o.urgency]);const notary=(o.service.includes('notary')||o.service==='Notary only')?p.notary*o.documents.length+(o.copies-1)*p.copy*o.documents.length:0;const delivery=(o.delivery||o.service==='Courier only')?p.delivery:0;const total=Math.round((base+review+rush+notary+delivery)*100);return {words,base,review,rush,notary,delivery,total,manual:o.service==='Additional services'||notary>0||delivery>0,days:{Standard:5,Priority:3,Express:1}[o.urgency]};}
export function money(cents:number,currency='EUR',p=defaultPricing){const conversion=currency==='USD'?p.usd:currency==='ILS'?p.ils:1;return new Intl.NumberFormat('en',{style:'currency',currency}).format(cents/100*conversion);}
