// Minimal, standards-based OOXML exports. ZIP entries are stored (not compressed).
// All document text is XML-escaped; no macros, formulas, hyperlinks or executable content.
export const xml=(s:string)=>s.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const enc=new TextEncoder();
function crc(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function pack(n:number,size:number){const a=new Uint8Array(size);const v=new DataView(a.buffer);if(size===2)v.setUint16(0,n,true);else v.setUint32(0,n,true);return a;}
function concat(parts:Uint8Array[]){const result=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let offset=0;for(const p of parts){result.set(p,offset);offset+=p.length;}return result;}
export function zip(files:Record<string,string>){const parts:Uint8Array[]=[];const directory:Uint8Array[]=[];let offset=0;for(const [path,text] of Object.entries(files)){const name=enc.encode(path),data=enc.encode(text),checksum=crc(data);const header=concat([pack(0x04034b50,4),pack(20,2),pack(0x800,2),pack(0,2),pack(0,2),pack(33,2),pack(checksum,4),pack(data.length,4),pack(data.length,4),pack(name.length,2),pack(0,2),name]);parts.push(header,data);directory.push(concat([pack(0x02014b50,4),pack(20,2),pack(20,2),pack(0x800,2),pack(0,2),pack(0,2),pack(33,2),pack(checksum,4),pack(data.length,4),pack(data.length,4),pack(name.length,2),pack(0,2),pack(0,2),pack(0,2),pack(0,2),pack(0,4),pack(offset,4),name]));offset+=header.length+data.length;}const central=concat(directory);return concat([...parts,central,pack(0x06054b50,4),pack(0,2),pack(0,2),pack(directory.length,2),pack(directory.length,2),pack(central.length,4),pack(offset,4),pack(0,2)]);}
const relationships='http://schemas.openxmlformats.org/package/2006/relationships';
export function docx(title:string,text:string,notice:string,rtl=false){const paragraph=(s:string,bold=false)=>`<w:p><w:pPr>${rtl?'<w:bidi/>':''}</w:pPr><w:r><w:rPr>${bold?'<w:b/>':''}${rtl?'<w:rtl/>':''}</w:rPr><w:t xml:space="preserve">${xml(s)}</w:t></w:r></w:p>`;return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':`<Relationships xmlns="${relationships}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,'word/document.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraph(title,true)}${paragraph(notice)}${text.split('\n').map(s=>paragraph(s)).join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`});}
export function xlsx(rows:string[][]){const col=(i:number):string=>i<26?String.fromCharCode(65+i):col(Math.floor(i/26)-1)+String.fromCharCode(65+i%26);return zip({'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':`<Relationships xmlns="${relationships}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Projects" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':`<Relationships xmlns="${relationships}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,'xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((row,i)=>`<row r="${i+1}">${row.map((cell,j)=>`<c r="${col(j)}${i+1}" t="inlineStr"><is><t xml:space="preserve">${xml(cell)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col((rows[0]?.length||1)-1)}${rows.length}"/></worksheet>`});}
