import {getUser} from '@/lib/account';
import {defaultPricing} from './catalog';
import {runtime,db} from './runtime';
export {runtime,db};
export function failure(e:unknown){if(e instanceof SyntaxError)return Response.json({error:'The request is not valid JSON.'},{status:400});console.error('Verba request failed',e instanceof Error?e.message:'Unknown error');return Response.json({error:e instanceof HttpError?e.message:'Unable to complete this request. Your changes have not been discarded; please try again.'},{status:e instanceof HttpError?e.status:503});}
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
// Accepts the browser Origin when it matches this site. Behind a TLS-terminating proxy
// (Render), the public origin comes from the Host header and X-Forwarded-Proto.
export function allowedOrigins(r:Request){const h=r.headers;const set=new Set<string>([new URL(r.url).origin]);const host=h.get('x-forwarded-host')?.split(',')[0].trim()||h.get('host');const proto=h.get('x-forwarded-proto')?.split(',')[0].trim()||new URL(r.url).protocol.replace(':','');if(host)set.add(`${proto}://${host}`);for(const configured of [runtime().APP_ORIGIN,runtime().RENDER_EXTERNAL_URL])if(configured){try{set.add(new URL(configured).origin);}catch{}}return set;}
export function sameOrigin(r:Request){const origin=r.headers.get('origin');if(origin&&!allowedOrigins(r).has(origin))throw new HttpError(403,'Request origin not allowed');}
// Client address for rate limiting, as reported by the hosting proxy.
export function clientAddress(r:Request){const h=r.headers;return h.get('cf-connecting-ip')||h.get('true-client-ip')||h.get('x-forwarded-for')?.split(',')[0].trim()||'shared';}
export async function context(r?:Request){if(r&&r.method!=='GET')sameOrigin(r);const u=await getUser();if(!u)throw new HttpError(401,'Sign in to continue');const email=u.email.toLowerCase();let membership:any=await db().prepare('SELECT * FROM members WHERE email = ? ORDER BY CASE role WHEN \'admin\' THEN 0 ELSE 1 END LIMIT 1').bind(email).first();if(!membership){const id=u.userId;const stamp=new Date().toISOString();await db().batch([db().prepare('INSERT INTO workspaces (id,owner,name,pricing,created) VALUES (?,?,?,?,?) ON CONFLICT DO NOTHING').bind(id,id,'Verba workspace',JSON.stringify(defaultPricing),stamp),db().prepare('INSERT INTO members (id,workspace,email,role,name,area) VALUES (?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(crypto.randomUUID(),id,email,'admin',u.fullName||email,'')]);membership=await db().prepare('SELECT * FROM members WHERE workspace = ? AND email = ?').bind(id,email).first();}const workspace:any=await db().prepare('SELECT * FROM workspaces WHERE id = ?').bind(membership.workspace).first();return {u,member:membership,workspace,pricing:JSON.parse(workspace.pricing),admin:membership.role==='admin'};}
export async function access(c:Awaited<ReturnType<typeof context>>,id:string){const o:any=await db().prepare('SELECT * FROM orders WHERE id = ? AND workspace = ?').bind(id,c.workspace.id).first();if(!o)throw new HttpError(404,'Order not found');if(!c.admin&&o.owner!==c.u.userId&&o.assignee!==c.member.email&&o.courier!==c.member.email)throw new HttpError(403,'This order is not assigned to you');return o;}
export function publicOrder(o:any,c?:Awaited<ReturnType<typeof context>>){const payload=JSON.parse(o.payload);if(c?.member.role==='courier'){return {...o,total:0,assignee:null,payload:{title:'Document delivery',service:'Courier only',sector:'',source:'',targets:[],documents:[],level:'',urgency:payload.urgency,validation:false,delivery:true,pickup:payload.pickup,dropoff:payload.dropoff,name:payload.name,email:payload.email,phone:payload.phone,notes:'',agreed:true}};}return {...o,payload};}
export function admin(c:Awaited<ReturnType<typeof context>>){if(!c.admin)throw new HttpError(403,'Administrator access required');}
export function event(workspace:string,order:string,actor:string,action:string){return db().prepare('INSERT INTO events (id,workspace,order_id,actor,action,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),workspace,order,actor,action,new Date().toISOString());}
