'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Check,Clock3,Trash2,MailCheck,Save,Search} from 'lucide-react';
import {toast} from 'sonner';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Pick,Field,CheckField,Pill,api,json} from '../verba-ui';
import {AddressFields,PhoneField,CountrySelect} from '../fields';
import {useT} from '../i18n';
import {currencies,defaultPricing,normalizeAddress,type Address,type Pricing,type Factors} from '@/lib/catalog';
import {splitPhone} from '@/lib/geo';
import DataTable,{type Column} from './data-table';
import {MemberDialog,InviteButton} from './views-deliveries';
import type {WorkspaceInfo,MemberInfo} from './types';

export function TeamView({ws,reload}:{ws:WorkspaceInfo;reload:()=>void}){
  const {t}=useT();const [edit,setEdit]=useState<Partial<MemberInfo>|null>(null);
  const cols:Column<MemberInfo>[]=[{key:'name',label:t('Name'),value:m=>m.name},{key:'email',label:t('Email'),value:m=>m.email},{key:'role',label:t('Role'),value:m=>t(m.role),render:m=><Pill tone={m.role}>{m.role}</Pill>,filter:'select'},{key:'area',label:t('Area of activity'),value:m=>m.area},{key:'phone',label:t('Phone'),value:m=>m.phone,hidden:true},{key:'status',label:t('Status'),value:m=>m.active?t('Active'):t('Not active'),filter:'select'},{key:'account',label:t('Account'),value:m=>m.has_account?t('Registered'):t('No account yet'),filter:'select'},
    {key:'actions',label:t('Actions'),value:()=>'',filter:'none',render:m=>m.email===ws.user.email?<span className="muted">{t('You')}</span>:<div className="row-actions" onClick={e=>e.stopPropagation()}><button className="text-link" onClick={()=>setEdit(m)}>{t('Edit')}</button>{!m.has_account&&<InviteButton email={m.email}/>}<button className="text-link danger-link" onClick={async()=>{if(!window.confirm(t('Remove access for {name}?',{name:m.name})))return;try{const r=await api('/api/team?email='+encodeURIComponent(m.email),{method:'DELETE'});toast.success(r.deactivated?t('Member deactivated (kept for reports)'):t('Member removed'));reload();}catch(e){toast.error(t((e as Error).message));}}}><Trash2 size={13}/>{t('Remove')}</button></div>}];
  return <section className="panel"><div className="panel-heading"><div><h2>{t('Your people')}</h2><p className="muted">{t('Company staff, translators, notaries, couriers and customers, each with the right access.')}</p></div></div>
    <DataTable id="team" title={t('Team')} rows={ws.members} columns={cols} rowKey={m=>m.email} exportable={false} toolbar={<button className="button primary small" onClick={()=>setEdit({role:'staff',active:1})}><Plus size={15}/>{t('Add member')}</button>}/>
    <p className="fine-print">{t('Customers can also create their own accounts on the website. Invitation links expire after 24 hours.')}</p>
    <MemberDialog value={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);reload();}}/></section>;
}

const priceLabels:Record<keyof typeof defaultPricing,string>={professional:'Professional translation · EUR per word',student:'Student translation · EUR per word',machine:'Machine translation · EUR per word',validation:'Validation / language review · EUR per word',notary:'Default notary fee · EUR per document',copy:'Extra notarized copy · EUR',delivery:'Local courier trip · EUR',minimum:'Minimum translation charge · EUR',usd:'USD per EUR (fallback)',ils:'ILS per EUR (fallback)',certificateProfessional:'Certificate page, professional · EUR',certificateStudent:'Certificate page, student · EUR',dtpPage:'Layout and formatting (DTP) · EUR per page',courierInternational:'International courier trip · EUR',nextDay:'Next-day delivery supplement · EUR',sameDay:'Same-day delivery supplement · EUR',roundTrip:'Round-trip multiplier (courier only)',priority:'Priority urgency supplement (0.25 = 25%)',express:'Express urgency supplement (0.5 = 50%)'};
const factorGroups:{key:keyof Factors;label:string;hint:string}[]=[
  {key:'sectors',label:'Translation field multipliers',hint:'1 = standard price, 1.2 = 20% more'},
  {key:'languages',label:'Target language multipliers',hint:'Languages not listed use 1'},
  {key:'formats',label:'File format multipliers',hint:'For example, scanned images may take longer'},
  {key:'documentTypes',label:'Document type multipliers',hint:'Document or certificate type name = multiplier'},
  {key:'customerTypes',label:'Customer type multipliers',hint:'new, existing (ordered before), organization (business account)'},
  {key:'countries',label:'Country of the work request multipliers',hint:'Two-letter country code, for example IL, US'},
  {key:'notaryTypes',label:'Notary fee per document (EUR)',hint:'By notarial service type'},
  {key:'notaryPer100',label:'Notary fee per additional 100 words (EUR)',hint:'Beyond the first 100 words'},
  {key:'capacity',label:'Words per working day by level',hint:'Used to calculate delivery days'},
  {key:'rates',label:'Reference exchange rates (per 1 EUR)',hint:'Used when live rates are off or unavailable'},
];
function MapEditor({value,onChange,label,hint}:{value:Record<string,number>;onChange:(v:Record<string,number>)=>void;label:string;hint:string}){
  const {t}=useT();const [k,setK]=useState('');const [v,setV]=useState('1');
  return <div className="map-editor"><h4>{t(label)}</h4><p className="fine-print">{t(hint)}</p>{Object.entries(value).map(([key,num])=><div className="map-row" key={key}><span>{t(key)}</span><input type="number" step="0.01" min={0} value={num} aria-label={key} onChange={e=>onChange({...value,[key]:Number(e.target.value)})}/><button type="button" aria-label={t('Remove')} onClick={()=>{const n={...value};delete n[key];onChange(n);}}><Trash2 size={13}/></button></div>)}
    <div className="map-row add"><input placeholder={t('Name')} value={k} onChange={e=>setK(e.target.value)}/><input type="number" step="0.01" min={0} value={v} onChange={e=>setV(e.target.value)}/><button type="button" aria-label={t('Add')} disabled={!k.trim()} onClick={()=>{onChange({...value,[k.trim()]:Number(v)});setK('');}}><Plus size={13}/></button></div></div>;
}
type Texts={sources:string[];builtin:{en:Record<string,string>;he:Record<string,string>};overrides:{lang:string;source:string;value:string}[]};
function TextsEditor(){
  const {t}=useT();const [data,setData]=useState<Texts|null>(null);const [q,setQ]=useState('');const [drafts,setDrafts]=useState<Record<string,string>>({});const [page,setPage]=useState(0);
  const load=()=>api('/api/texts').then(d=>setData(d as unknown as Texts)).catch(e=>toast.error(t(e.message)));
  // eslint-disable-next-line react-hooks/exhaustive-deps -- load once
  useEffect(()=>{void load();},[]);
  const current=(lang:'en'|'he',s:string)=>drafts[lang+'|'+s]??data?.overrides.find(o=>o.lang===lang&&o.source===s)?.value??(lang==='he'?data?.builtin.he[s]??'':s);
  const list=useMemo(()=>(data?.sources||[]).filter(s=>!q||s.toLowerCase().includes(q.toLowerCase())||(data?.builtin.he[s]||'').includes(q)),[data,q]);
  async function save(lang:'en'|'he',s:string){try{await api('/api/texts',json({lang,source:s,value:current(lang,s)},'PUT'));toast.success(t('Text saved. Visitors see it within a minute.'));await load();setDrafts(d=>{const n={...d};delete n[lang+'|'+s];return n;});}catch(e){toast.error(t((e as Error).message));}}
  if(!data)return <p className="muted">{t('Loading…')}</p>;
  const shown=list.slice(page*40,page*40+40);
  return <div className="texts-editor"><p className="muted">{t('Every interface text in English and Hebrew. Change a text and save it; leave it empty to restore the original.')}</p><div className="search-field"><Search size={16}/><input placeholder={t('Search texts…')} value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/></div>
    <table className="dyn-table texts-table"><thead><tr><th>English</th><th>עברית</th></tr></thead><tbody>{shown.map(s=><tr key={s}>{(['en','he'] as const).map(lang=><td key={lang} dir={lang==='he'?'rtl':'ltr'}><textarea rows={Math.min(4,Math.ceil(s.length/60))} value={current(lang,s)} onChange={e=>setDrafts(d=>({...d,[lang+'|'+s]:e.target.value}))}/>{drafts[lang+'|'+s]!==undefined&&<button className="button primary small" onClick={()=>save(lang,s)}><Save size={13}/>{t('Save')}</button>}</td>)}</tr>)}</tbody></table>
    <div className="pager"><button className="button secondary small" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('Previous')}</button><span>{t('{from}–{to} of {total}',{from:page*40+1,to:Math.min(list.length,page*40+40),total:list.length})}</span><button className="button secondary small" disabled={(page+1)*40>=list.length} onClick={()=>setPage(p=>p+1)}>{t('Next')}</button></div></div>;
}
type Notice={id:string;recipient:string;channel:string;template:string;subject:string;status:string;detail:string;created:string};
export function SettingsView({ws,reload}:{ws:WorkspaceInfo;reload:()=>void}){
  const {t,lang}=useT();const [name,setName]=useState(ws.workspace);const [pricing,setPricing]=useState<Pricing>(ws.pricing);const [config,setConfig]=useState(ws.config);const [busy,setBusy]=useState(false);const [log,setLog]=useState<Notice[]>([]);
  const office=normalizeAddress({country:ws.pricing.officeCountry,...(config.officeAddress||{})});
  async function save(){setBusy(true);try{const {ratesDate,...clean}=pricing as Pricing&{ratesDate?:string};void ratesDate;await api('/api/workspace',json({name,pricing:clean,config},'PATCH'));toast.success(t('Settings saved'));reload();}catch(e){toast.error(t((e as Error).message));}finally{setBusy(false);}}
  const c=ws.connections as Record<string,unknown>;
  const conn:[string,string,boolean][]=[['Accounts & sign-up','Customers register with email and password; staff by invitation',true],['Orders, documents and running numbers','Stored in the database with private file storage',true],['Upload safety scan','Built-in check for scripts and active content in PDF and Word files',true],['External antivirus','CLOUDMERSIVE_API_KEY',!!c.scanner],['Email (SMTP)','SMTP_URL or SMTP_HOST, MAIL_FROM',!!c.email],['SMS','TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM',!!c.sms],['WhatsApp','TWILIO_WHATSAPP_FROM',!!c.whatsapp],['Viber / WeChat','Requires a Viber or WeChat business account',false],['Captcha','TURNSTILE_SITE_KEY, TURNSTILE_SECRET_KEY',!!c.captcha],['Social login',(c.social as string[]||[]).length?(c.social as string[]).join(', '):'GOOGLE_CLIENT_ID / FACEBOOK_CLIENT_ID / X_CLIENT_ID and secrets',(c.social as string[]||[]).length>0],['Daily exchange rates',c.rates?t('European Central Bank rates of {date}',{date:String(c.rates)}):'European Central Bank daily rates (not reachable yet)',!!c.rates],['AI translation','OPENAI_API_KEY',!!c.translation],['Main system handoff','MAIN_SYSTEM_WEBHOOK_URL, MAIN_SYSTEM_WEBHOOK_SECRET',!!c.mainSystem],['Payments','On hold',false],['Courier company booking (DHL / UPS / FedEx)','Requires business accounts',false]];
  const logCols:Column<Notice>[]=[{key:'created',label:t('Date'),value:n=>new Date(n.created).toLocaleString(lang==='he'?'he-IL':'en-GB')},{key:'channel',label:t('Channel'),value:n=>n.channel,filter:'select'},{key:'recipient',label:t('Recipient'),value:n=>n.recipient},{key:'template',label:t('Message'),value:n=>n.subject||n.template},{key:'status',label:t('Status'),value:n=>t(n.status),filter:'select'},{key:'detail',label:t('Details'),value:n=>t(n.detail)}];
  return <Tabs defaultValue="workspace" onValueChange={v=>{if(v==='log')api('/api/notifications').then(r=>setLog(r as unknown as Notice[])).catch(()=>{});}}><TabsList className="settings-tabs"><TabsTrigger value="workspace">{t('Workspace')}</TabsTrigger><TabsTrigger value="prices">{t('Prices')}</TabsTrigger><TabsTrigger value="factors">{t('Price factors')}</TabsTrigger><TabsTrigger value="texts">{t('Languages & texts')}</TabsTrigger><TabsTrigger value="connections">{t('Connections')}</TabsTrigger><TabsTrigger value="log">{t('Notifications')}</TabsTrigger></TabsList>
    <TabsContent value="workspace"><section className="panel settings-panel"><Field label={t('Company / workspace name')}><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label={t('Email for new orders and inquiries')}><input type="email" value={config.notifyEmail||''} onChange={e=>setConfig({...config,notifyEmail:e.target.value})} placeholder={ws.user.email}/></Field>
      <h4>{t('Office address (courier start and end point)')}</h4><AddressFields idPrefix="office" value={office} onChange={a=>{setConfig({...config,officeAddress:a});setPricing({...pricing,officeCountry:a.country});}} showWindow={false}/>
      <div className="two-col"><Field label={t('Local courier name')}><input value={pricing.localCarrier} onChange={e=>setPricing({...pricing,localCarrier:e.target.value})}/></Field><Pick label={t('International carrier')} value={pricing.internationalCarrier} onChange={v=>setPricing({...pricing,internationalCarrier:v})} options={['DHL','UPS','FedEx'].map(x=>({value:x,label:x}))}/></div>
      <h4>{t('Customer area banner')}</h4><Field label={t('Banner title')}><input value={config.bannerTitle||''} maxLength={120} onChange={e=>setConfig({...config,bannerTitle:e.target.value})}/></Field><Field label={t('Banner text')}><textarea rows={2} maxLength={400} value={config.bannerText||''} onChange={e=>setConfig({...config,bannerText:e.target.value})}/></Field>
      <CheckField label={t('Use daily exchange rates')} checked={config.liveRates!==false} onChange={v=>setConfig({...config,liveRates:v})}>{t('Prices are set in EUR. Customers can see them in their local currency.')}</CheckField>
      <button className="button primary" disabled={busy} onClick={save}>{t('Save settings')}</button></section></TabsContent>
    <TabsContent value="prices"><section className="panel settings-panel"><p className="muted">{t('These rates calculate new quotes. Existing orders keep their saved amount.')}</p><div className="two-col">{(Object.keys(defaultPricing) as (keyof typeof defaultPricing)[]).filter(k=>k!=='usd'&&k!=='ils').map(k=><Field key={k} label={t(priceLabels[k])}><input type="number" step="0.001" min={0} value={pricing[k]} onChange={e=>setPricing({...pricing,[k]:Number(e.target.value)})}/></Field>)}</div><button className="button primary" disabled={busy} onClick={save}>{t('Save prices')}</button></section></TabsContent>
    <TabsContent value="factors"><section className="panel settings-panel"><p className="muted">{t('The price of the work is affected by these metrics (spec: customer type, document type, languages, file format, layout, country of origin, notary services).')}</p><div className="factor-grid">{factorGroups.map(g=><MapEditor key={g.key} label={g.label} hint={g.hint} value={pricing.factors[g.key] as Record<string,number>} onChange={v=>setPricing({...pricing,factors:{...pricing.factors,[g.key]:v}})}/>)}
      <div className="map-editor"><h4>{t('Official notary price lists by country')}</h4><p className="fine-print">{t('Fee per document by notarial service type, used when the document is for that country.')}</p>{Object.entries(pricing.factors.notaryCountries).map(([country,list])=><div key={country} className="notary-country"><b>{country}</b><MapEditor label="" hint="" value={list} onChange={v=>setPricing({...pricing,factors:{...pricing.factors,notaryCountries:{...pricing.factors.notaryCountries,[country]:v}}})}/></div>)}<CountrySelect label={t('Add a country')} value="IL" onChange={v=>setPricing({...pricing,factors:{...pricing.factors,notaryCountries:{...pricing.factors.notaryCountries,[v]:{...(pricing.factors.notaryCountries[v]||pricing.factors.notaryTypes)}}}})}/></div></div>
      <button className="button primary" disabled={busy} onClick={save}>{t('Save price factors')}</button></section></TabsContent>
    <TabsContent value="texts"><section className="panel settings-panel"><TextsEditor/></section></TabsContent>
    <TabsContent value="connections"><section className="panel settings-panel"><p className="muted">{t('Services connect when their keys are added to the hosting environment (Render and Netlify settings). Until then, messages are logged under Notifications.')}</p>{conn.map(([n,text,ready])=><div className="connection" key={n}><span className={ready?'connection-ready':'connection-pending'}>{ready?<Check size={17}/>:<Clock3 size={17}/>}</span><div><b>{t(n)}</b><small>{t(text)}</small></div><Pill tone={ready?'ready':'pending'}>{ready?t('Ready'):t('Setup needed')}</Pill></div>)}</section></TabsContent>
    <TabsContent value="log"><section className="panel"><DataTable id="notifications" title={t('Notifications')} rows={log} columns={logCols} rowKey={n=>n.id} exportable={false}/></section></TabsContent>
  </Tabs>;
}
type Profile={firstName:string;lastName:string;email:string;emailVerified:boolean;phone:string|null;company:string;customerType:string;country:string;address:Address;language:string;notify:string[];currency:string;role:string};
export function ProfileView({ws}:{ws:WorkspaceInfo}){
  const {t}=useT();const [p,setP]=useState<Profile|null>(null);const [phone,setPhone]=useState({prefix:'+972',number:''});const [busy,setBusy]=useState(false);const [pw,setPw]=useState({current:'',next:''});
  useEffect(()=>{api('/api/profile').then(d=>{const pr=d as unknown as Profile;setP(pr);setPhone(pr.phone?splitPhone(pr.phone):{prefix:'+972',number:''});}).catch(e=>toast.error(t(e.message)));},[t]);
  if(!p)return <p className="muted">{t('Loading…')}</p>;
  const set=<K extends keyof Profile>(k:K,v:Profile[K])=>setP(x=>x?{...x,[k]:v}:x);
  const conn=ws.connections as Record<string,unknown>;
  const channels:[string,string,boolean][]=[['email','Email',true],['sms','SMS',!!conn.sms],['whatsapp','WhatsApp',!!conn.whatsapp],['viber','Viber',false],['wechat','WeChat',false]];
  return <div className="settings-grid"><section className="panel settings-panel"><h2>{t('Personal information')}</h2>
    <div className="two-col"><Field label={t('First name')}><input value={p.firstName} onChange={e=>set('firstName',e.target.value)} maxLength={60}/></Field><Field label={t('Last name')}><input value={p.lastName} onChange={e=>set('lastName',e.target.value)} maxLength={60}/></Field></div>
    <Field label={t('Email address')}><input value={p.email} disabled/></Field>{!p.emailVerified&&<p className="fine-print verify-note"><MailCheck size={14}/>{t('Your email address is not confirmed yet.')} <button className="text-link" onClick={async()=>{try{const r=await api('/api/auth/verify',{method:'PUT'});toast.success(r.sent?t('We sent you a confirmation link.'):t('Email is not connected yet.'));}catch(e){toast.error(t((e as Error).message));}}}>{t('Send confirmation link')}</button></p>}
    <PhoneField label={t('Phone number')} prefix={phone.prefix} number={phone.number} onChange={(a,b)=>setPhone({prefix:a,number:b})}/>
    <div className="two-col"><Pick label={t('Customer type')} value={p.customerType} onChange={v=>set('customerType',v)} options={[{value:'Private',label:t('Private')},{value:'Business',label:t('Business')}]}/><Field label={t('Company')}><input value={p.company} maxLength={120} onChange={e=>set('company',e.target.value)}/></Field></div>
    <h4>{t('Address')}</h4><AddressFields idPrefix="profile" value={p.address} onChange={a=>setP(x=>x?{...x,address:a,country:a.country}:x)} showWindow={false} showContact={false}/>
    <div className="two-col"><Pick label={t('Language')} value={p.language} onChange={v=>set('language',v)} options={[{value:'en',label:'English'},{value:'he',label:'עברית'}]}/><Pick label={t('Display currency')} value={p.currency} onChange={v=>set('currency',v)} options={currencies.map(c=>({value:c,label:c}))}/></div>
    <h4>{t('How should we notify you about your orders?')}</h4><div className="channel-list">{channels.map(([k,label,ready])=><CheckField key={k} label={t(label)} checked={p.notify.includes(k)} disabled={k==='email'} onChange={v=>set('notify',v?[...p.notify,k]:p.notify.filter(x=>x!==k))}>{ready?'':t('Not connected yet')}</CheckField>)}</div>
    <button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/profile',json({firstName:p.firstName,lastName:p.lastName,phonePrefix:phone.prefix,phone:phone.number,company:p.company,customerType:p.customerType,country:p.address.country||p.country,address:p.address,language:p.language,notify:p.notify,currency:p.currency},'PATCH'));toast.success(t('Personal information saved'));if(p.language!==document.documentElement.lang)location.reload();}catch(e){toast.error(t((e as Error).message));}finally{setBusy(false);}}}>{t('Save')}</button></section>
    <section className="panel settings-panel"><h2>{t('Change password')}</h2><Field label={t('Current password')}><input type="password" autoComplete="current-password" value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})}/></Field><Field label={t('New password')}><input type="password" autoComplete="new-password" minLength={10} value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})}/></Field><button className="button secondary" disabled={busy||!pw.current||pw.next.length<10} onClick={async()=>{setBusy(true);try{await api('/api/profile',json({currentPassword:pw.current,newPassword:pw.next},'PATCH'));setPw({current:'',next:''});toast.success(t('Password changed'));}catch(e){toast.error(t((e as Error).message));}finally{setBusy(false);}}}>{t('Change password')}</button></section></div>;
}
