import {pgTable,text,integer,index,uniqueIndex,customType} from 'drizzle-orm/pg-core';
const bytea=customType<{data:Buffer}>({dataType(){return 'bytea';}});
export const workspaces=pgTable('workspaces',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),pricing:text('pricing').notNull(),created:text('created').notNull()});
export const members=pgTable('members',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),email:text('email').notNull(),role:text('role').notNull(),name:text('name').notNull(),area:text('area').notNull().default('')},t=>[uniqueIndex('members_workspace_email').on(t.workspace,t.email),index('members_email').on(t.email)]);
export const orders=pgTable('orders',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),reference:text('reference').notNull(),payload:text('payload').notNull(),total:integer('total').notNull(),status:text('status').notNull(),payment:text('payment').notNull().default('Not requested'),assignee:text('assignee'),courier:text('courier'),shipment:text('shipment').notNull().default('Awaiting assignment'),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('orders_workspace').on(t.workspace),index('orders_owner').on(t.owner),uniqueIndex('orders_reference').on(t.reference)]);
export const files=pgTable('files',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),orderId:text('order_id'),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),purpose:text('purpose').notNull(),created:text('created').notNull()},t=>[index('files_order').on(t.orderId)]);
// Private document bytes (replaces the object bucket). One row per uploaded file.
export const fileObjects=pgTable('file_objects',{id:text('id').primaryKey(),data:bytea('data').notNull(),contentType:text('content_type').notNull(),created:text('created').notNull()});
export const messages=pgTable('messages',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),orderId:text('order_id').notNull(),sender:text('sender').notNull(),name:text('name').notNull(),body:text('body').notNull(),created:text('created').notNull()},t=>[index('messages_order').on(t.orderId)]);
export const events=pgTable('events',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),orderId:text('order_id').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),created:text('created').notNull()},t=>[index('events_order').on(t.orderId)]);
export const translations=pgTable('translations',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),requestKey:text('request_key').notNull(),title:text('title').notNull(),source:text('source').notNull(),target:text('target').notNull(),sector:text('sector').notNull(),tone:text('tone').notNull(),fileId:text('file_id'),sourceText:text('source_text').notNull().default(''),segments:text('segments').notNull().default('[]'),draft:text('draft').notNull().default('[]'),result:text('result').notNull().default('[]'),issues:text('issues').notNull().default('[]'),glossary:text('glossary').notNull().default('[]'),state:text('state').notNull(),phase:text('phase').notNull(),cursor:integer('cursor').notNull().default(0),lease:text('lease'),leaseUntil:text('lease_until'),error:text('error'),failures:integer('failures').notNull().default(0),sourceConfirmed:integer('source_confirmed').notNull().default(0),reviewer:text('reviewer'),reviewerNote:text('reviewer_note'),approvedAt:text('approved_at'),version:integer('version').notNull().default(1),model:text('model').notNull(),quote:text('quote'),quoteAcceptedAt:text('quote_accepted_at'),usage:text('usage').notNull().default('{}'),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('translations_workspace_owner').on(t.workspace,t.owner),uniqueIndex('translations_request').on(t.owner,t.requestKey)]);
export const glossary=pgTable('glossary',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),sourceLanguage:text('source_language').notNull(),targetLanguage:text('target_language').notNull(),sector:text('sector').notNull(),sourceTerm:text('source_term').notNull(),targetTerm:text('target_term').notNull(),created:text('created').notNull()},t=>[index('glossary_workspace').on(t.workspace),uniqueIndex('glossary_term_pair').on(t.workspace,t.sourceLanguage,t.targetLanguage,t.sector,t.sourceTerm)]);

export const accounts=pgTable('accounts',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),recoveryHash:text('recovery_hash').notNull(),created:text('created').notNull()});
export const sessions=pgTable('sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull(),expires:text('expires').notNull(),created:text('created').notNull()},t=>[index('sessions_account').on(t.accountId)]);
export const authLimits=pgTable('auth_limits',{id:text('id').primaryKey(),count:integer('count').notNull().default(0),expires:text('expires').notNull()});
export const accountInvites=pgTable('account_invites',{tokenHash:text('token_hash').primaryKey(),workspace:text('workspace').notNull(),email:text('email').notNull(),name:text('name').notNull(),expires:text('expires').notNull(),usedAt:text('used_at')});
