import {pgTable,pgSequence,text,integer,index,uniqueIndex,primaryKey,customType} from 'drizzle-orm/pg-core';
import {sql} from 'drizzle-orm';
const bytea=customType<{data:Buffer}>({dataType(){return 'bytea';}});
export const workspaces=pgTable('workspaces',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),pricing:text('pricing').notNull(),config:text('config').notNull().default('{}'),created:text('created').notNull()});
export const members=pgTable('members',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),email:text('email').notNull(),role:text('role').notNull(),name:text('name').notNull(),area:text('area').notNull().default(''),phone:text('phone').notNull().default(''),address:text('address').notNull().default(''),businessNumber:text('business_number').notNull().default(''),active:integer('active').notNull().default(1)},t=>[uniqueIndex('members_workspace_email').on(t.workspace,t.email),index('members_email').on(t.email)]);
export const orders=pgTable('orders',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),reference:text('reference').notNull(),payload:text('payload').notNull(),total:integer('total').notNull(),status:text('status').notNull(),payment:text('payment').notNull().default('Not requested'),assignee:text('assignee'),courier:text('courier'),shipment:text('shipment').notNull().default('Awaiting assignment'),number:integer('number'),dueDate:text('due_date'),vendor:text('vendor'),paidAt:text('paid_at'),currency:text('currency').notNull().default('EUR'),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('orders_workspace').on(t.workspace),index('orders_owner').on(t.owner),uniqueIndex('orders_reference').on(t.reference),uniqueIndex('orders_number').on(t.number)]);
export const files=pgTable('files',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),orderId:text('order_id'),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),purpose:text('purpose').notNull(),created:text('created').notNull()},t=>[index('files_order').on(t.orderId)]);
// Private document bytes (replaces the object bucket). One row per uploaded file.
export const fileObjects=pgTable('file_objects',{id:text('id').primaryKey(),data:bytea('data').notNull(),contentType:text('content_type').notNull(),created:text('created').notNull()});
export const messages=pgTable('messages',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),orderId:text('order_id').notNull(),sender:text('sender').notNull(),name:text('name').notNull(),body:text('body').notNull(),created:text('created').notNull()},t=>[index('messages_order').on(t.orderId)]);
export const events=pgTable('events',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),orderId:text('order_id').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),created:text('created').notNull()},t=>[index('events_order').on(t.orderId)]);
export const translations=pgTable('translations',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),owner:text('owner').notNull(),requestKey:text('request_key').notNull(),title:text('title').notNull(),source:text('source').notNull(),target:text('target').notNull(),sector:text('sector').notNull(),tone:text('tone').notNull(),fileId:text('file_id'),sourceText:text('source_text').notNull().default(''),segments:text('segments').notNull().default('[]'),draft:text('draft').notNull().default('[]'),result:text('result').notNull().default('[]'),issues:text('issues').notNull().default('[]'),glossary:text('glossary').notNull().default('[]'),state:text('state').notNull(),phase:text('phase').notNull(),cursor:integer('cursor').notNull().default(0),lease:text('lease'),leaseUntil:text('lease_until'),error:text('error'),failures:integer('failures').notNull().default(0),sourceConfirmed:integer('source_confirmed').notNull().default(0),reviewer:text('reviewer'),reviewerNote:text('reviewer_note'),approvedAt:text('approved_at'),version:integer('version').notNull().default(1),model:text('model').notNull(),quote:text('quote'),quoteAcceptedAt:text('quote_accepted_at'),usage:text('usage').notNull().default('{}'),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('translations_workspace_owner').on(t.workspace,t.owner),uniqueIndex('translations_request').on(t.owner,t.requestKey)]);
export const glossary=pgTable('glossary',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),sourceLanguage:text('source_language').notNull(),targetLanguage:text('target_language').notNull(),sector:text('sector').notNull(),sourceTerm:text('source_term').notNull(),targetTerm:text('target_term').notNull(),created:text('created').notNull()},t=>[index('glossary_workspace').on(t.workspace),uniqueIndex('glossary_term_pair').on(t.workspace,t.sourceLanguage,t.targetLanguage,t.sector,t.sourceTerm)]);

export const accounts=pgTable('accounts',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),recoveryHash:text('recovery_hash').notNull(),firstName:text('first_name').notNull().default(''),lastName:text('last_name').notNull().default(''),phone:text('phone'),emailVerifiedAt:text('email_verified_at'),company:text('company').notNull().default(''),customerType:text('customer_type').notNull().default('Private'),country:text('country').notNull().default('IL'),address:text('address').notNull().default('{}'),language:text('language').notNull().default('en'),notify:text('notify').notNull().default('["email"]'),currency:text('currency').notNull().default('EUR'),disabledAt:text('disabled_at'),created:text('created').notNull()},t=>[uniqueIndex('accounts_phone').on(t.phone).where(sql`phone IS NOT NULL`)]);
export const sessions=pgTable('sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull(),expires:text('expires').notNull(),created:text('created').notNull()},t=>[index('sessions_account').on(t.accountId)]);
export const authLimits=pgTable('auth_limits',{id:text('id').primaryKey(),count:integer('count').notNull().default(0),expires:text('expires').notNull()});
export const accountInvites=pgTable('account_invites',{tokenHash:text('token_hash').primaryKey(),workspace:text('workspace').notNull(),email:text('email').notNull(),name:text('name').notNull(),expires:text('expires').notNull(),usedAt:text('used_at')});
// Running numbers for orders and shipments (shown as VB-2026-001001 and SH-001001).
export const orderNumberSeq=pgSequence('order_number_seq',{startWith:1001});
export const shipmentNumberSeq=pgSequence('shipment_number_seq',{startWith:1001});
// One record per courier job. Origin and destination are JSON addresses.
export const shipments=pgTable('shipments',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),number:integer('number').notNull(),orderId:text('order_id'),customerAccount:text('customer_account'),customerName:text('customer_name').notNull(),customerEmail:text('customer_email').notNull().default(''),customerPhone:text('customer_phone').notNull().default(''),status:text('status').notNull(),deliveryDate:text('delivery_date'),sameDay:integer('same_day').notNull().default(0),nextDay:integer('next_day').notNull().default(0),urgency:text('urgency').notNull().default('Standard'),type:text('type').notNull().default('1 way'),operator:text('operator').notNull().default(''),courier:text('courier'),returnCourier:text('return_courier'),origin:text('origin').notNull(),destination:text('destination').notNull(),sum:integer('sum').notNull().default(0),international:integer('international').notNull().default(0),tracking:text('tracking').notNull().default(''),notes:text('notes').notNull().default(''),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('shipments_workspace').on(t.workspace),index('shipments_order').on(t.orderId),index('shipments_courier').on(t.courier),uniqueIndex('shipments_number').on(t.number)]);
// Support and pre-order chat. A conversation belongs to an account or to a guest browser token.
export const conversations=pgTable('conversations',{id:text('id').primaryKey(),workspace:text('workspace').notNull(),accountId:text('account_id'),guestHash:text('guest_hash'),name:text('name').notNull(),email:text('email').notNull().default(''),subject:text('subject').notNull().default(''),kind:text('kind').notNull().default('support'),orderId:text('order_id'),status:text('status').notNull().default('open'),assignee:text('assignee'),lastMessageAt:text('last_message_at').notNull(),staffReadAt:text('staff_read_at'),customerReadAt:text('customer_read_at'),created:text('created').notNull()},t=>[index('conversations_workspace').on(t.workspace,t.lastMessageAt),index('conversations_account').on(t.accountId),index('conversations_guest').on(t.guestHash)]);
export const conversationMessages=pgTable('conversation_messages',{id:text('id').primaryKey(),conversationId:text('conversation_id').notNull(),senderKind:text('sender_kind').notNull(),senderEmail:text('sender_email').notNull().default(''),senderName:text('sender_name').notNull(),body:text('body').notNull(),created:text('created').notNull()},t=>[index('conversation_messages_conversation').on(t.conversationId,t.created)]);
// Delivery log for email, SMS and messaging notifications (sent, skipped when not connected, or failed).
export const notifications=pgTable('notifications',{id:text('id').primaryKey(),workspace:text('workspace'),recipient:text('recipient').notNull(),channel:text('channel').notNull(),template:text('template').notNull(),subject:text('subject').notNull().default(''),status:text('status').notNull(),detail:text('detail').notNull().default(''),created:text('created').notNull()},t=>[index('notifications_workspace').on(t.workspace,t.created)]);
export const emailTokens=pgTable('email_tokens',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull(),purpose:text('purpose').notNull(),expires:text('expires').notNull(),usedAt:text('used_at'),created:text('created').notNull()},t=>[index('email_tokens_account').on(t.accountId)]);
export const oauthIdentities=pgTable('oauth_identities',{provider:text('provider').notNull(),subject:text('subject').notNull(),accountId:text('account_id').notNull(),email:text('email').notNull().default(''),created:text('created').notNull()},t=>[primaryKey({columns:[t.provider,t.subject]})]);
export const settings=pgTable('settings',{key:text('key').primaryKey(),value:text('value').notNull(),updated:text('updated').notNull()});
// Administrator-entered interface texts per language, keyed by the English source text.
export const uiTexts=pgTable('ui_texts',{lang:text('lang').notNull(),source:text('source').notNull(),value:text('value').notNull(),updated:text('updated').notNull()},t=>[primaryKey({columns:[t.lang,t.source]})]);
// Pieces of a large upload, joined when the last piece arrives (keeps each request small).
export const uploadChunks=pgTable('upload_chunks',{uploadId:text('upload_id').notNull(),idx:integer('idx').notNull(),ownerKey:text('owner_key').notNull(),data:bytea('data').notNull(),created:text('created').notNull()},t=>[primaryKey({columns:[t.uploadId,t.idx]})]);
