// Regenerates lib/pdf-fonts.ts: Noto Sans subsets (Latin, Latin Extended, Cyrillic,
// Hebrew) embedded as base64, so PDF quotes and reports work on serverless hosts
// without reading font files from disk. Run after updating @fontsource packages.
import {readFileSync,writeFileSync} from 'node:fs';
const dir=p=>new URL('../node_modules/@fontsource/'+p,import.meta.url);
const fonts={};
for(const weight of [400,700]){
  for(const subset of ['latin','latin-ext','cyrillic'])fonts[`${subset}-${weight}`]=dir(`noto-sans/files/noto-sans-${subset}-${weight}-normal.woff`);
  fonts[`hebrew-${weight}`]=dir(`noto-sans-hebrew/files/noto-sans-hebrew-hebrew-${weight}-normal.woff`);
}
let out='// Generated by scripts/build-fonts.mjs from @fontsource/noto-sans and @fontsource/noto-sans-hebrew (SIL Open Font License 1.1).\n/* eslint-disable */\nexport const pdfFonts:Record<string,string>={\n';
for(const [k,u] of Object.entries(fonts))out+=`  ${JSON.stringify(k)}:${JSON.stringify(readFileSync(u).toString('base64'))},\n`;
writeFileSync(new URL('../lib/pdf-fonts.ts',import.meta.url),out+'};\n');
console.log('Wrote lib/pdf-fonts.ts with',Object.keys(fonts).length,'fonts');
